import React, { useEffect, useRef, useState } from 'react';
import mermaid from 'mermaid';

// Initialize mermaid
mermaid.initialize({
  startOnLoad: false,
  theme: 'dark',
  securityLevel: 'loose',
  flowchart: {
    useMaxWidth: true,
    htmlLabels: true
  }
});

interface MermaidChartProps {
  chart: string;
  onNodeHover?: (nodeKey: string | null, clientX: number, clientY: number) => void;
}

export const MermaidChart: React.FC<MermaidChartProps> = ({ chart, onNodeHover }) => {
  const containerRef = useRef<HTMLDivElement>(null);
  const [svgContent, setSvgContent] = useState<string>('');
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (!chart) return;
    
    const renderChart = async () => {
      setError(null);
      const uniqueId = `mermaid-${Math.floor(Math.random() * 1000000)}`;
      try {
        let cleanChart = chart.trim();
        // Strip markdown code block wrappers if any
        if (cleanChart.startsWith('```mermaid')) {
          cleanChart = cleanChart.replace(/^```mermaid\n?/, '');
        }
        if (cleanChart.endsWith('```')) {
          cleanChart = cleanChart.replace(/```$/, '');
        }
        cleanChart = cleanChart.trim();

        // Render the diagram
        const { svg } = await mermaid.render(uniqueId, cleanChart);
        setSvgContent(svg);
      } catch (err: any) {
        console.error('Mermaid render error:', err);
        setError(err.message || 'Failed to render Mermaid diagram');
        
        // Cleanup potential phantom element generated by mermaid in body
        const phantom = document.getElementById(uniqueId);
        if (phantom) {
          phantom.remove();
        }
        const phantomBind = document.getElementById(`d${uniqueId}`);
        if (phantomBind) {
          phantomBind.remove();
        }
      }
    };

    renderChart();
  }, [chart]);

  // Keep onNodeHover in a ref to avoid re-binding listeners on parent re-renders
  const onNodeHoverRef = useRef(onNodeHover);
  useEffect(() => {
    onNodeHoverRef.current = onNodeHover;
  }, [onNodeHover]);

  // Set up event listeners for hover events on nodes
  useEffect(() => {
    if (!svgContent || !containerRef.current) return;

    const container = containerRef.current;
    
    // Find all node groups (usually <g class="node"> in flowchart SVG)
    const nodes = container.querySelectorAll('.node');

    const getCleanNodeKey = (target: HTMLElement): string | null => {
      const gNode = target.closest('.node') as HTMLElement;
      if (!gNode) return null;

      // Check id attribute
      const idAttr = gNode.getAttribute('id') || '';
      
      // Look for our specific node keys in the ID (e.g. docker_xxx, pod_xxx, etc.)
      const match = idAttr.match(/(docker|pod|svc|deploy|node)_[a-zA-Z0-9_.-]+/);
      if (match) {
        return match[0];
      }

      // Fallback: use text content inside the node to match
      const textNode = gNode.querySelector('.nodeLabel, text');
      if (textNode) {
        const txt = textNode.textContent || '';
        return `text_${txt.trim()}`;
      }

      return null;
    };

    const handleMouseEnter = (e: Event) => {
      const key = getCleanNodeKey(e.currentTarget as HTMLElement);
      if (key && onNodeHoverRef.current) {
        const mouseEvent = e as MouseEvent;
        onNodeHoverRef.current(key, mouseEvent.clientX, mouseEvent.clientY);
      }
    };

    const handleMouseMove = (e: Event) => {
      const key = getCleanNodeKey(e.currentTarget as HTMLElement);
      if (key && onNodeHoverRef.current) {
        const mouseEvent = e as MouseEvent;
        onNodeHoverRef.current(key, mouseEvent.clientX, mouseEvent.clientY);
      }
    };

    const handleMouseLeave = () => {
      if (onNodeHoverRef.current) {
        onNodeHoverRef.current(null, 0, 0);
      }
    };

    nodes.forEach(node => {
      node.addEventListener('mouseenter', handleMouseEnter);
      node.addEventListener('mousemove', handleMouseMove);
      node.addEventListener('mouseleave', handleMouseLeave);
    });

    return () => {
      nodes.forEach(node => {
        node.removeEventListener('mouseenter', handleMouseEnter);
        node.removeEventListener('mousemove', handleMouseMove);
        node.removeEventListener('mouseleave', handleMouseLeave);
      });
    };
  }, [svgContent]);

  if (error) {
    return (
      <div className="mermaid-error">
        <div className="error-title">⚠️ Graph syntax error</div>
        <pre className="error-code">{chart}</pre>
      </div>
    );
  }

  return (
    <div 
      className="mermaid-container" 
      ref={containerRef} 
      dangerouslySetInnerHTML={{ __html: svgContent || '<div class="chart-loading">Rendering visualization...</div>' }} 
    />
  );
};
export default MermaidChart;
